import Head from "next/head";
import formImage from "../public/form.png";
import Image from "next/image";
import { useFormik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
import { motion as m } from "framer-motion";

export default function Home() {
  //formik logics

  const router = useRouter();

  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "United Kingdom",
      terms: "",
    },

    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, "must be 20 characters or less")
        .required("name is required"),
      email: Yup.string()
        .email("invalid email address")
        .max(20, "must be 20 characters or less")
        .required("email is required"),
      terms: Yup.array().required("Terms of service must be chcked"),
    }),

    onSubmit: (values) => {
      console.log(values);
      router.push({ pathname: "/success", query: values });
    },
  });

  console.log(formik.errors);

  console.log("formik-values");

  validationSchema: Yup.object({
    name: Yup.string()
      .max(20, "Name must be 20 characters or less.")
      .required("Name is required"),
    email: Yup.string()
      .email("Invalid email address")
      .required("Email is required"),
    terms: Yup.array().required("Terms of service must be checked"),

    onSubmit: (values) => {
      console.log("form submitted");
      console.log(values);
      router.push({ pathname: "/success", query: values });
    },
  });

  return (
    <m.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="absolute w-full"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" h-screen items-center flex justify-center min-w-fit">
        <form
          className="bg-white flex rounded-lg w-1/2 font-latoRegular"
          onSubmit={formik.handleSubmit}
        >
          <div className="flex-1 text-gray-700 p-20">
            <h1 className="text-3xl font-latoBold pb-2">lets get started</h1>
            <p className="text-lg text-gray-500">Join today!</p>
            <div className="mt-6">
              {/* Name */}
              <div className="pb-4">
                <label
                  className={`block font-latoBold text-sm pb-2 ${
                    formik.touched.name && formik.errors.name
                      ? "text-red-400"
                      : ""
                  }`}
                  htmlFor="name"
                >
                  {formik.touched.name && formik.errors.name
                    ? formik.errors.name
                    : "Name"}
                </label>
                <input
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500"
                  type="text"
                  name="name"
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  placeholder="Enter your name"
                  onBlur={formik.handleBlur}
                />
              </div>

              {/* Email */}
              <div className="pb-4">
                <label
                  className={`block font-latoBold text-sm pb-2 ${
                    formik.touched.email && formik.errors.email
                      ? "text-red-400"
                      : "Name"
                  }`}
                  htmlFor="email"
                >
                  {formik.touched.email && formik.errors.email
                    ? formik.errors.email
                    : "Email"}
                </label>
                <input
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500"
                  type="email"
                  name="email"
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  placeholder="Enter your email"
                  onBlur={formik.handleBlur}
                />
              </div>

              {/* countries */}
              <div className="pb-4">
                <label
                  className="block font-latoBold text-sm pb-2"
                  htmlFor="country"
                >
                  Countries
                </label>

                <select
                  name="country"
                  className="border-2 border-gray-500 p-2 rounded-md w-1/2 focus:border-teal-500 focus:ring-teal-500"
                >
                  <option value="">United States</option>
                  <option value="">United Kingdom</option>
                  <option value="">Germany</option>
                  <option value="">Norway</option>
                </select>
              </div>

              <div className="pb-4">
                <label
                  className={`block font-latoBold text-sm pb-2 ${
                    formik.touched.terms && formik.errors.terms
                      ? "text-red-400"
                      : "terms"
                  }`}
                  htmlFor="terms"
                >
                  {formik.touched.terms && formik.errors.terms
                    ? formik.errors.terms
                    : "Terms of service"}
                </label>
                <p className="text-sm mb-4 text-gray-500 font-latoBold">
                  I have read and agreed to the terms of service
                </p>
                <div className="flex items-center">
                  <input
                    type="checkbox"
                    name="terms"
                    value="checked"
                    onChange={formik.handleChange}
                    className="h-5 w-5 text-teal-500 border-2 focus:border-teal-500 focus:ring-teal:50"
                  />
                  <p className="text-sm font-latoBold text-gray-500 "></p>
                </div>
              </div>
              <button
                type="submit"
                className="bg-teal-500 font-latoBold text-sm text-white py-3 mt-6 rounded-lg w-full"
              >
                Start learning today!
              </button>
            </div>
          </div>
          <div className="flex-1 relative">
            <Image
              alt="form-learn"
              src={formImage}
              className="object-cover rounded-lg"
              priority={true}
              fill
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw"
              placeholder="blur"
              as="true"
            />
          </div>
        </form>
      </main>
    </m.div>
  );
}
